### PR TITLE
Make compile under Ubuntu20.04

### PR DESCRIPTION
**Pull request by maltewi**
First commit is straight forward.

second commit:
```
 38%] Linking CXX executable test_boost_graph
/usr/bin/ld: ../../core/libslam3d_core.so: undefined reference to `LZ4_decompress_safe_continue'
/usr/bin/ld: ../../core/libslam3d_core.so: undefined reference to `LZ4_decompress_safe'
/usr/bin/ld: ../../core/libslam3d_core.so: undefined reference to `LZ4_compress_HC_continue'
/usr/bin/ld: ../../core/libslam3d_core.so: undefined reference to `LZ4_resetStreamHC'
/usr/bin/ld: ../../core/libslam3d_core.so: undefined reference to `LZ4_setStreamDecode'
collect2: error: ld returned 1 exit status
make[2]: *** [slam3d/graph/boost/CMakeFiles/test_boost_graph.dir/build.make:91: slam3d/graph/boost/test_boost_graph] Error 1
make[1]: *** [CMakeFiles/Makefile2:282: slam3d/graph/boost/CMakeFiles/test_boost_graph.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
The dependency to lz4 comes from flann. If flann was integrated via pkg-config the missing dependency would be passed correctly.

```bash
pkg-config --libs flann
-llz4 -lflann -lflann_cpp
```

Since pkg-config was not used in any CMakeLists.txt in this project and the dependency to flann comes somehow via pcl, I refrained to use it here.

### CODE REVIEW

**Comment by skasperski** [comment]
I think the Flann issue was already adressed in devel branch. Can you check whether it builds in 20.04?

**Comment by maltewi** [comment]
Yes, it builds on devel. What do you propose? Switch to devel or wait for a (soon) updated master?

**Comment by skasperski** [comment]
I suggest staying on master with the CI, because devel is not supposed to be stable. If you tested on 20.04, I could update master right away. Did you also test orogen/slam3d?

**Comment by maltewi** [comment]
Did no functional tests so far. I can only confirm, that compiling works. Since there are a few other issues to be sorted out with u20.04 in my stack, it will take a bit until I could report on functional tests.

**Comment by skasperski** [comment]
I did functional tests in 18.04, so I guess when it compiles under 20.04 as well, it should be fine. I just updated lib and orogen now.

**Comment by maltewi** [comment]
Master compiles now. Thanks. I'll close this.
